general:
  regression_datasets: ['SARS', 'MERS']
  path_to_regression_datasets: '/home/jannikroth/work/20_FragShapley/FragShapley/0_datasets/regression/'
  smiles_column: 'canonical_smiles'
  y_column: 'pIC50'
  set_column: 'set'

  expected_value: 'empty'

  random_state: 42

  results_folder: 'mpnn_regression_potency'

MPNN:
  mpnnr_model_parameter: {n_fc_layers: 3,  
                          fc_hidden: 256,
                          message_passing_steps: 3,
                          dropout: 0.2, 
                          lr: 0.0001,
                          edge_feat_hidden: 32,
                          node_feat_hidden: 64,
                          }
  accelerator: 'auto'
  max_epochs: 150
  batch_size: 8
