general:
  classification_datasets: ['Hansen']
  path_to_classification_datasets: '/home/jannikroth/work/20_FragShapley/FragShapley/0_datasets/classification/'
  smiles_column: 'nonstereo_aromatic_smiles'
  y_column: 'mutagenicity'
  n_cv: 5
  expected_value: 'empty'
  random_state: 42
  results_folder: 'mpnn_classification_hansen'

MPNN:
  mpnnc_model_parameter: {n_fc_layers: 1,  
                          fc_hidden: 128,
                          message_passing_steps: 2,
                          lr: 0.001,
                          edge_feat_hidden: 64,
                          node_feat_hidden: 32,
                          }
  accelerator: 'auto'
  max_epochs: 50
  batch_size: 16 
